'use client';
import {useState,useRef,useMemo,useCallback,useEffect} from 'react';
import {Box,Download,ArrowUpRight,Layers3,Plus,Minus,Maximize2,Focus,Grid2X2,Eye,EyeOff,Navigation2,Mouse,Move,Sun,TreePine,Route,GitBranch,Image as ImageIcon,Check,ChevronRight,SlidersHorizontal} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {UrbanViewer,type ViewerApi,type SceneDefinition} from '@/components/urban-viewer';
import {CONCEPTS,CONCEPT_BY_ID,type ConceptId} from '@/lib/concept-data';
import {createConceptModel} from '@/lib/concept-model';

export default function ConceptWorkspace(){
 const [id,setId]=useState<ConceptId>('vibrant'),[view,setView]=useState<'iso'|'top'>('iso'),[mode,setMode]=useState<'material'|'clay'|'wire'>('material');
 const [selected,setSelected]=useState('v-mall'),[ready,setReady]=useState(false),[labels,setLabels]=useState(true),[connections,setConnections]=useState(true);
 const [visibility,setVisibility]=useState({buildings:true,parks:true,roads:true,curbs:true}),[daylight,setDaylight]=useState(13);
 const [dialog,setDialog]=useState<'reference'|'export'|null>(null),[exporting,setExporting]=useState(false),[message,setMessage]=useState('');
 const viewer=useRef<ViewerApi>(null),concept=CONCEPT_BY_ID[id],building=concept.buildings.find(b=>b.id===selected)??concept.buildings.find(b=>b.id===concept.initial)!;
 const onReady=useCallback(()=>setReady(true),[]);
 const definition=useMemo<SceneDefinition>(()=>({id:'concept-'+id,title:concept.name,buildings:concept.buildings,createModel:()=>createConceptModel(id),labels:[{text:'河岸步道',x:155,z:551,y:7},{text:id==='vibrant'?'河岸運動空間':id==='skybridge'?'架空步道網絡':'立體城市連廊',x:id==='vibrant'?464:610,z:id==='vibrant'?470:440,y:id==='vibrant'?8:id==='skybridge'?24:40,visibleWith:id==='vibrant'?'parks':'connections'}],roadLabels:[{text:'CASTLE PEAK ROAD',x:548,z:26,width:80},{text:'KAU YUK ROAD',x:510,z:624,width:60},{text:'TAI TONG ROAD',x:975,z:343,width:51,angle:Math.PI/2}],target:[0,id==='vertical'?38:12,30],span:id==='vertical'?390:330,width:535}),[id,concept]);
 function choose(next:ConceptId){if(next===id)return;setReady(false);setId(next);setSelected(CONCEPT_BY_ID[next].initial);setView('iso');setMessage('');}
 useEffect(()=>{if(!message)return;const timer=window.setTimeout(()=>setMessage(''),5000);return()=>clearTimeout(timer);},[message]);
 async function download(){if(!viewer.current||!ready)return;setExporting(true);try{await viewer.current.exportGLB();setDialog(null);setMessage(concept.name+'模型已下載，可匯入 Blender。');}catch{setMessage('模型匯出未完成，請再試一次。');}finally{setExporting(false);}}
 return <main className="studio concept-studio">
  <header className="main-header"><a className="brand" href="/" aria-label="回到元朗街區"><Box size={30} strokeWidth={1.55}/><strong>街區<span>URBAN<br/>STUDIO</span></strong></a><nav className="studio-nav" aria-label="工作空間"><a href="/">街區現況</a><a href="/concepts" aria-current="page">概念模型<span>03</span></a></nav><div className="header-status"><span className="status-dot"/>{ready?'模型已就緒':'正在建立模型'}</div><button className="export-button" aria-label="匯出至 Blender" disabled={!ready} onClick={()=>setDialog('export')}><Download size={15}/><span>匯出至 Blender</span><ArrowUpRight size={14}/></button></header>
  <div className="concept-mobile-switch"><RadioGroup value={id} onValueChange={v=>choose(v as ConceptId)} aria-label="選擇概念模型">{CONCEPTS.map((c,i)=><label key={c.id} className={id===c.id?'active':''}><RadioGroupItem value={c.id} className="sr-only"/><span>0{i+1}</span>{c.name}</label>)}</RadioGroup></div>
  <div className="workspace">
   <aside className="left-panel concept-list"><div className="project-heading"><div className="eyebrow">COMMUNITY CONCEPTS</div><h1>三種社區，一座城市</h1><p>從概念圖走進立體空間</p></div><div className="concept-cards"><RadioGroup value={id} onValueChange={v=>choose(v as ConceptId)} aria-label="概念方案">{CONCEPTS.map((c,i)=><label key={c.id} className={'concept-card '+(id===c.id?'selected':'')}><RadioGroupItem value={c.id} className="sr-only"/><div className="concept-card-image"><img src={c.image} alt={c.name+'概念模型原圖'}/><span>0{i+1}</span>{id===c.id&&<i><Check size={13}/></i>}</div><div className="concept-card-name"><strong>{c.name}</strong><ChevronRight size={14}/></div><small>{c.en}</small></label>)}</RadioGroup></div><div className="sidebar-note"><ImageIcon size={16}/><span>依三張概念圖片分別重建。<br/>尺寸、樓高與細節為示意。</span></div></aside>
   <section className="viewport" aria-label={concept.name+'互動模型'}><div className="viewport-toolbar"><Layers3 size={16}/><span className="toolbar-label">概念重建</span><div className="toolbar-divider"/><button className={'icon-button '+(labels?'active':'')} aria-label="切換模型標籤" title="顯示或隱藏標籤" aria-pressed={labels} onClick={()=>setLabels(v=>!v)}>{labels?<Eye size={16}/>:<EyeOff size={16}/>}</button><button className={'icon-button '+(connections?'active':'')} aria-label="切換橋樑與連廊" title="顯示或隱藏橋樑" aria-pressed={connections} onClick={()=>setConnections(v=>!v)}><GitBranch size={16}/></button><Tabs value={view} onValueChange={v=>setView(v as typeof view)} className="camera-tabs"><TabsList aria-label="模型視角"><TabsTrigger value="iso"><Box size={13}/>立體視圖</TabsTrigger><TabsTrigger value="top"><Grid2X2 size={13}/>俯視圖</TabsTrigger></TabsList></Tabs></div>
    <div className="scene-shell"><UrbanViewer key={id} ref={viewer} definition={definition} view={view} mode={mode} selected={building.id} visibility={visibility} labels={labels} connections={connections} heightScale={1} daylight={daylight} onSelect={setSelected} onReady={onReady}/>
     <div className="scene-caption"><div className="eyebrow">CONCEPT MODEL / 0{CONCEPTS.findIndex(c=>c.id===id)+1}</div><h2>{concept.name}</h2><small>{concept.en}</small><br/><div className="scene-tag"><span style={{background:concept.accent}}/>依概念原圖重建</div></div>
     <div className="compass"><span>N</span><div className="compass-rose"><Navigation2 data-compass size={24} strokeWidth={1.4}/></div></div>
     <div className="navigation-tools"><button className="icon-button" aria-label="放大模型" title="放大" onClick={()=>viewer.current?.zoom(1.2)}><Plus size={17}/></button><button className="icon-button" aria-label="縮小模型" title="縮小" onClick={()=>viewer.current?.zoom(1/1.2)}><Minus size={17}/></button><button className="icon-button" aria-label="聚焦選取建築" title="聚焦選取建築" onClick={()=>viewer.current?.focus()}><Focus size={16}/></button><button className="icon-button" aria-label="重設模型全景" title="重設全景" onClick={()=>viewer.current?.reset()}><Maximize2 size={15}/></button></div>
     <button className="reference-map concept-reference" onClick={()=>setDialog('reference')} aria-label={'開啟'+concept.name+'概念原圖'}><img src={concept.image} alt={concept.name+'原圖縮圖'}/><span className="map-caption"><span>概念原圖對照</span><Maximize2 size={12}/></span></button>
     <div className="view-help"><span><Mouse size={12}/>拖曳旋轉</span><span><Move size={12}/>右鍵平移</span><span><Plus size={12}/>滾輪縮放</span></div>
    </div>
   </section>
   <aside className="right-panel concept-inspector"><div className="inspector-heading"><SlidersHorizontal size={15}/>概念與場景</div><section className="inspector-section"><div className="eyebrow">DESIGN CONCEPT</div><h2>{concept.name}</h2><p className="concept-description">{concept.description}</p><ul className="concept-features">{concept.features.map(f=><li key={f}><span/>{f}</li>)}</ul></section>
    <section className="inspector-section"><h3><Box size={14}/>已選取物件</h3><div className="concept-object"><strong>{building.name}</strong><span>{building.kind==='wood'?'木質建築':building.kind==='blue'?'藍色地標':building.kind==='station'?'交通設施':building.kind==='brown'?'模組建築':'住宅及地標'}</span></div><div className="data-row"><span>示意高度</span><span className="value-chip">{building.h.toFixed(1)} u</span></div><button className="focus-button" disabled={!visibility.buildings} onClick={()=>viewer.current?.focus()}><Focus size={14}/>聚焦此建築</button></section>
    <section className="inspector-section"><h3><Layers3 size={14}/>場景圖層</h3><div className="concept-layer"><Box size={14}/>建築<Switch checked={visibility.buildings} onCheckedChange={v=>setVisibility(s=>({...s,buildings:v}))} aria-label="顯示概念建築"/></div><div className="concept-layer"><GitBranch size={14}/>{id==='vibrant'?'河岸橋樑':'空中連廊'}<Switch checked={connections} onCheckedChange={setConnections} aria-label="顯示橋樑連廊"/></div><div className="concept-layer"><TreePine size={14}/>地景與分區<Switch checked={visibility.parks} onCheckedChange={v=>setVisibility(s=>({...s,parks:v}))} aria-label="顯示地景與分區"/></div><div className="concept-layer"><Route size={14}/>道路與路緣<Switch checked={visibility.roads} onCheckedChange={v=>setVisibility(s=>({...s,roads:v,curbs:v}))} aria-label="顯示道路與路緣"/></div></section>
    <section className="inspector-section"><h3><Sun size={14}/>模型外觀</h3><RadioGroup className="mode-buttons" value={mode} onValueChange={v=>setMode(v as typeof mode)} aria-label="概念模型外觀">{[{id:'material',label:'原圖配色'},{id:'clay',label:'白模'},{id:'wire',label:'線框'}].map(m=><label key={m.id} className={'mode-option '+(mode===m.id?'active':'')}><RadioGroupItem value={m.id} className="sr-only"/><Box size={17}/>{m.label}</label>)}</RadioGroup><div className="slider-label"><span>日照時間</span><b>{daylight}:00</b></div><Slider min={8} max={17} step={1} value={[daylight]} onValueChange={v=>setDaylight(Array.isArray(v)?v[0]:v)} aria-label="概念模型日照時間"/></section>
   </aside>
  </div>
  <footer className="status-bar"><span><span className="status-dot"/>{ready?'模型就緒':'建立中'}</span><span>{concept.buildings.length} 組建築</span><span>{concept.bridges.length} 段連接路徑</span><span className="status-end">概念圖重建 · 示意比例</span></footer>
  {message&&<div className="toast-message" role="status">{message}</div>}
  <Dialog open={dialog!==null} onOpenChange={open=>{if(!open&&!exporting)setDialog(null);}}><DialogContent className={'dialog-large '+(dialog==='export'?'export-dialog':'concept-image-dialog')}>
   {dialog==='reference'?<><DialogTitle>{concept.name} · 概念原圖</DialogTitle><DialogDescription>依據這張圖片重建建築量體、地面分區與橋樑。單張圖片無法確定的尺寸及隱藏細節採示意處理。</DialogDescription><img className="concept-original" src={concept.image} alt={concept.name+'完整概念模型圖片'}/><a className="concept-image-link" href={concept.image} target="_blank" rel="noreferrer">開啟完整原圖<ArrowUpRight size={14}/></a></>:<><DialogTitle>匯出「{concept.name}」</DialogTitle><DialogDescription>下載目前可見的建築、橋樑與地景，保留獨立物件及材質。</DialogDescription><div className="export-format"><Box size={36}/><div><strong>Blender 相容模型 · .glb</strong><p>可繼續編輯建築及連廊，並儲存為 .blend。</p></div></div><ol className="export-steps"><li>下載目前的概念模型。</li><li>在 Blender 選擇「檔案 → 匯入 → glTF 2.0」。</li><li>選取 .glb 檔案開始編輯。</li></ol><p className="dialog-note">模型依單張概念圖重建，並非精確測繪或原始模型檔。</p><button className="export-button" onClick={download} disabled={exporting||!ready}><Download size={16}/>{exporting?'正在準備模型…':'下載此概念模型'}</button></>}
  </DialogContent></Dialog>
 </main>;
}


