'use client';
/* oxlint-disable react/react-compiler -- Pointer transactions and canvas exports retain imperative state in refs. */
import {useEffect,useRef,useState,type PointerEvent as PE} from 'react';
import {Box,MousePointer2,Map,Route,Building2,Link2,TreePine,Undo2,Redo2,Download,Upload,ImageDown,Trash2,Copy,RotateCw,Plus,Minus,Maximize2,Minimize2,Save,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {StudioNav} from '@/components/studio-nav';
import {Localized,useLanguage} from '@/components/language-provider';
import {DistrictPreview,type PreviewApi} from '@/components/district-preview';
import {DistrictPlan,ModelThumbnail} from '@/components/district-plan';
import {MODELS,MODEL_MAP,RIVER,ZONES,emptyDesign,uid,snap,round,footprint,overlaps,counts,bridgeGeometry,validate,warnings,riverOverlaps,blockedRoutes,roadLength,parseDesign,type Design,type Point,type Building,type ZoneKind} from '@/lib/district-design';
import {districtText,DISTRICT_ZH} from '@/lib/district-copy';
import {download,filename,exportPlan,exportParts} from '@/lib/district-export';
import './district-designer.css';
type Tool='select'|'zone'|'road'|'path'|'building'|'bridge'|'tree'|'bench';
type Selection={kind:'buildings'|'zones'|'roads'|'bridges'|'decorations';id:string};
type Drag={point:Point;original:Design;selection?:Selection;vertex?:number};
const STORAGE='yuen-long-district-design-v1';
const zoneNames:Record<ZoneKind,string>={residential:'Residential',commercial:'Commercial',community:'Community',green:'Green space',plaza:'Plaza'};
function NumberField({label,value,min,max,onCommit,unit='mm'}:{label:string;value:number;min:number;max:number;onCommit:(n:number)=>void;unit?:string}){const [text,setText]=useState(String(round(value)));useEffect(()=>setText(String(round(value))),[value]);return <label className="dd-number"><span>{label}</span><div><input aria-label={label} type="number" min={min} max={max} step="1" value={text} onChange={e=>setText(e.target.value)} onBlur={()=>{const n=Number(text);if(text.trim()&&Number.isFinite(n)&&n>=min&&n<=max)onCommit(n);setText(String(round(value)));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><small>{unit}</small></div></label>;}
export default function DistrictDesigner(){
 const language=useLanguage(),t=(key:string)=>districtText(key,language);
 const [design,setDesign]=useState<Design>(emptyDesign),[past,setPast]=useState<Design[]>([]),[future,setFuture]=useState<Design[]>([]),[ready,setReady]=useState(false),[broken,setBroken]=useState(''),[saved,setSaved]=useState('Ready');
 const [tool,setTool]=useState<Tool>('select'),[tab,setTab]=useState<'print'|'wood'>('print'),[modelId,setModelId]=useState('R1'),[zoneKind,setZoneKind]=useState<ZoneKind>('residential'),[routeWidth,setRouteWidth]=useState(15),[bridgeWidth,setBridgeWidth]=useState(16),[bridgeHeight,setBridgeHeight]=useState(30),[bridgeStart,setBridgeStart]=useState('');
 const [selected,setSelected]=useState<Selection|null>(null),[draft,setDraft]=useState<Point[]>([]),[preview,setPreview]=useState<Design|null>(null),[view,setView]=useState<'top'|'3d'>('top'),[expanded,setExpanded]=useState(false),[dimensions,setDimensions]=useState(true),[grid,setGrid]=useState(true),[zoom,setZoom]=useState(1),[viewCenter,setViewCenter]=useState<Point>({x:297,y:211}),[message,setMessage]=useState(''),[exporting,setExporting]=useState(false);
 const svg=useRef<SVGSVGElement>(null),drag=useRef<Drag|null>(null),file=useRef<HTMLInputElement>(null),three=useRef<PreviewApi>(null),c=counts(design);
 const [confirmation,setConfirmation]=useState<{message:string;resolve:(value:boolean)=>void}|null>(null);
 function ask(message:string){return new Promise<boolean>(resolve=>setConfirmation({message,resolve}));}
 function respond(value:boolean){confirmation?.resolve(value);setConfirmation(null);}
 const current=selected?design[selected.kind].find(o=>o.id===selected.id):null;
 function commit(next:Design){const error=validate(next);if(error){setMessage(error);return false;}setPast(p=>[...p,design].slice(-50));setFuture([]);setDesign(next);return true;}
 function undo(){if(!past.length)return;setFuture(f=>[design,...f]);setDesign({...past[past.length-1],name:design.name,className:design.className,group:design.group});setPast(p=>p.slice(0,-1));setPreview(null);setDraft([]);setSelected(null);}
 function redo(){if(!future.length)return;setPast(p=>[...p,design]);setDesign({...future[0],name:design.name,className:design.className,group:design.group});setFuture(f=>f.slice(1));setSelected(null);}
 function choose(next:Tool){setTool(next);if(next==='road')setRouteWidth(15);if(next==='path')setRouteWidth(8);setDraft([]);setBridgeStart('');setPreview(null);drag.current=null;if(next!=='select')setView('top');}
 function update(patch:Record<string,unknown>){if(selected)commit({...design,[selected.kind]:design[selected.kind].map(o=>o.id===selected.id?{...o,...patch}:o)} as Design);}
 async function remove(){if(!selected)return;if(selected.kind==='buildings'&&design.bridges.some(b=>b.from===selected.id||b.to===selected.id)&&!(await ask('Delete this building and its connected bridges?')))return;const next={...design,[selected.kind]:design[selected.kind].filter(o=>o.id!==selected.id)} as Design;if(selected.kind==='buildings')next.bridges=next.bridges.filter(b=>b.from!==selected.id&&b.to!==selected.id);if(commit(next))setSelected(null);}
 function duplicate(){if(!selected||!current||!['buildings','zones','decorations'].includes(selected.kind))return;const kind=selected.kind;if(kind==='buildings'){const m=MODEL_MAP[(current as Building).modelId];if(c[m.kind]>=(m.kind==='print'?6:4)){setMessage(m.kind==='print'?'Maximum 6 printed buildings.':'Maximum 4 wooden buildings.');return;}}for(let y=85;y<345;y+=10)for(let x=40;x<565;x+=10){const obj={...current,id:uid(),x,y};if(kind==='buildings'&&(overlaps(footprint(obj as Building),RIVER)||design.buildings.some(b=>overlaps(footprint(b),footprint(obj as Building)))))continue;const next={...design,[kind]:[...design[kind],obj]} as Design;if(!validate(next)){commit(next);setSelected({kind,id:obj.id});return;}}setMessage('No space nearby. Choose a different position.');}
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw){try{setDesign(parseDesign(JSON.parse(raw)));}catch{setBroken(raw);setSaved('An unreadable saved design was found. Download it before starting over.');}}}catch{setSaved('Local saving unavailable. Download your design to keep it.');}setReady(true);},[]);
 useEffect(()=>{if(!ready||broken)return;const timer=setTimeout(()=>{try{localStorage.setItem(STORAGE,JSON.stringify(design));setSaved('Saved in this browser');}catch{setSaved('Local saving unavailable. Download your design to keep it.');}},250);return()=>clearTimeout(timer);},[design,ready,broken]);
 useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),6000);return()=>clearTimeout(timer);},[message]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(confirmation)return;if((e.target as HTMLElement).closest('input,textarea,select,[contenteditable]'))return;if(e.key==='Escape'){setExpanded(false);choose('select');setSelected(null);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();if(e.shiftKey)redo();else undo();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}else if((e.key==='Delete'||e.key==='Backspace')&&selected){e.preventDefault();void remove();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 function point(e:PE):Point{const matrix=svg.current?.getScreenCTM();if(!matrix)return {x:0,y:0};const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());return {x:snap(p.x,grid),y:snap(p.y,grid)};}
 function down(e:PE<SVGSVGElement>){if(e.button!==0||!ready||broken)return;e.currentTarget.focus();const p=point(e),target=(e.target as Element).closest('[data-object]'),id=target?.getAttribute('data-object'),kind=target?.getAttribute('data-kind') as Selection['kind']|undefined,vertex=(e.target as Element).getAttribute('data-vertex');
  if(tool==='building'){const b={id:uid(),modelId,...p,rotation:0};if(commit({...design,buildings:[...design.buildings,b]}))setSelected({kind:'buildings',id:b.id});return;}
  if(tool==='tree'||tool==='bench'){const o={id:uid(),kind:tool,...p,rotation:0};if(commit({...design,decorations:[...design.decorations,o]}))setSelected({kind:'decorations',id:o.id});return;}
  if(tool==='road'||tool==='path'){if(!draft.length||Math.hypot(p.x-draft[draft.length-1].x,p.y-draft[draft.length-1].y)>.1)setDraft(d=>[...d,p]);return;}
  if(tool==='bridge'){if(kind!=='buildings'||!id){setMessage('Click two different buildings to connect a bridge.');return;}if(!bridgeStart){setBridgeStart(id);return;}const b={id:uid(),from:bridgeStart,to:id,width:bridgeWidth,height:bridgeHeight};if(commit({...design,bridges:[...design.bridges,b]})){setSelected({kind:'bridges',id:b.id});setBridgeStart('');}return;}
  if(tool==='zone'){drag.current={point:p,original:design};e.currentTarget.setPointerCapture(e.pointerId);return;}
  if(id&&kind){setSelected({kind,id});if(kind!=='bridges'){drag.current={point:p,original:design,selection:{kind,id},vertex:vertex!==null?Number(vertex):undefined};e.currentTarget.setPointerCapture(e.pointerId);}}else setSelected(null);
 }
 function moved(e:PE<SVGSVGElement>):Design|null{const transaction=drag.current;if(!transaction)return null;const p=point(e),dx=p.x-transaction.point.x,dy=p.y-transaction.point.y,original=transaction.original;if(!transaction.selection)return {...original,zones:[...original.zones,{id:'drawing-zone',kind:zoneKind,x:Math.min(p.x,transaction.point.x),y:Math.min(p.y,transaction.point.y),w:Math.abs(dx),d:Math.abs(dy)}]};const {kind,id}=transaction.selection;return {...original,[kind]:original[kind].map(o=>{if(o.id!==id)return o;if(kind==='roads'){const road=o as Design['roads'][number];return {...road,points:road.points.map((v,i)=>transaction.vertex===undefined?{x:v.x+dx,y:v.y+dy}:i===transaction.vertex?p:v)};}return {...o,x:(o as Point).x+dx,y:(o as Point).y+dy};})} as Design;}
 function up(e:PE<SVGSVGElement>){const transaction=drag.current;if(!transaction)return;const next=moved(e);drag.current=null;setPreview(null);if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId);if(!next)return;if(!transaction.selection){const z=next.zones[next.zones.length-1];if(z.w<5||z.d<5)return;z.id=uid();if(commit(next))setSelected({kind:'zones',id:z.id});}else if(JSON.stringify(next)!==JSON.stringify(design))commit(next);}
 function finishRoad(){if(draft.length<2){setMessage('Add at least two different points.');return;}const r={id:uid(),kind:tool==='path'?'path' as const:'road' as const,width:routeWidth,points:draft};if(commit({...design,roads:[...design.roads,r]})){choose('select');setSelected({kind:'roads',id:r.id});}}
 async function open(f:File){try{if(f.size>2_000_000)throw new Error('File is too large. Open a design file smaller than 2 MB.');const next=parseDesign(JSON.parse(await f.text()));if(design.buildings.length+design.zones.length+design.roads.length+design.decorations.length>0&&!(await ask('Replace this design with the selected file? You can undo this action.')))return;if(commit(next)){setBroken('');setSelected(null);choose('select');setMessage('Design loaded.');}}catch(err){setMessage(err instanceof Error&&err.message in DISTRICT_ZH?err.message:'Invalid design file. Your current design is unchanged.');}}
 function save(){download(new Blob([JSON.stringify(design,null,2)],{type:'application/json'}),filename(design)+'.json');setMessage('Design downloaded.');}
 async function image(){setExporting(true);try{if(view==='3d'){const url=three.current?.image();if(!url)throw new Error();download(url,filename(design)+'-3d.png');}else{if(!svg.current)throw new Error();await exportPlan(svg.current,filename(design));}setMessage('Image downloaded.');}catch{setMessage('Image export failed. Please try again.');}finally{setExporting(false);}}
 const instruction=tool==='select'?'Click a building, zone or decoration, then drag to move it.':tool==='zone'?'Drag a rectangle inside the site to create a zone.':tool==='building'?'Choose a model, then click inside the site to place it.':tool==='bridge'?(bridgeStart?'Now click the second building.':'Click two different buildings to connect a bridge.'):tool==='road'||tool==='path'?'Click to add corners. Finish the route when ready.':'Click inside the site to place a decoration.';
 const b=selected?.kind==='buildings'?design.buildings.find(x=>x.id===selected.id):undefined,z=selected?.kind==='zones'?design.zones.find(x=>x.id===selected.id):undefined,r=selected?.kind==='roads'?design.roads.find(x=>x.id===selected.id):undefined,bridge=selected?.kind==='bridges'?design.bridges.find(x=>x.id===selected.id):undefined,deco=selected?.kind==='decorations'?design.decorations.find(x=>x.id===selected.id):undefined;
 const collision=warnings(design),blocked=blockedRoutes(design),water=riverOverlaps(design),name=(id:string)=>language==='en'?MODEL_MAP[id].nameEn:MODEL_MAP[id].nameZh;
 const num=(label:string,value:number,min:number,max:number,onCommit:(n:number)=>void,unit='mm')=><NumberField key={label} label={t(label)} value={value} min={min} max={max} onCommit={onCommit} unit={unit}/>;
 return <main className={'district-studio'+(expanded?' dd-expanded':'')}>
  <header className="main-header"><Localized><div className="brand"><Box size={28}/><strong>元朗街區</strong></div></Localized><StudioNav current="district"/><span className="dd-header-note">A2 · 594 × 420 mm</span></header>
  <div className="dd-heading"><div><span className="eyebrow">DESIGN STUDIO / A2</span><h1>{t('District design')}</h1></div><div className="dd-quotas"><span className={c.print===6?'full':''}><i className="dd-print-dot"/>{t('Printed')} <b>{c.print} / 6</b></span><span className={c.wood===4?'full':''}><i className="dd-wood-dot"/>{t('Wooden')} <b>{c.wood} / 4</b></span></div><div className="dd-file-actions"><button onClick={save} disabled={!ready||!!broken}><Download size={16}/>{t('Save design')}</button><button onClick={()=>file.current?.click()}><Upload size={16}/>{t('Open design')}</button><input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void open(f);e.target.value='';}}/></div></div>
  {broken&&<div className="dd-alert">{t('An unreadable saved design was found. Download it before starting over.')}<button onClick={()=>download(new Blob([broken],{type:'application/json'}),'district-design-backup.json')}>{t('Download saved backup')}</button><button onClick={()=>setBroken('')}>{t('Start a new design')}</button></div>}
  <div className="dd-body"><aside className="dd-library" aria-label={t('Design tools')}><div className="dd-tools">{([{key:'select',icon:MousePointer2,label:'Select & move'},{key:'zone',icon:Map,label:'Zones'},{key:'road',icon:Route,label:'Roads'},{key:'building',icon:Building2,label:'Buildings'},{key:'bridge',icon:Link2,label:'Bridges'},{key:'tree',icon:TreePine,label:'Decorations'}] as const).map(({key,icon:Icon,label})=><button key={key} className={tool===key||(key==='road'&&tool==='path')||(key==='tree'&&tool==='bench')?'active':''} aria-pressed={tool===key} onClick={()=>choose(key)}><Icon size={20}/>{t(label)}</button>)}</div>
   {(tool==='building'||tool==='select')&&<><div className="dd-section-title"><h2>{t('Model library')}</h2><span>20</span></div><div className="dd-tabs">{(['print','wood'] as const).map(k=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{t(k==='print'?'Printed':'Wooden')}</button>)}</div><p className="dd-note">{t('Model dimensions: W × D × H. Base plates included.')}</p><div className="dd-model-grid">{MODELS.filter(m=>m.kind===tab).map(m=><button key={m.id} data-model={m.id} className={'dd-model '+(tool==='building'&&modelId===m.id?'active':'')} disabled={!ready||c[m.kind]>=(m.kind==='print'?6:4)} onClick={()=>{choose('building');setModelId(m.id);}}><ModelThumbnail model={m}/><strong>{m.id} <span>{name(m.id)}</span></strong><small>{m.width} × {m.depth} × {m.height} mm</small></button>)}</div><p className="dd-note">{t('One complete model counts as one building.')}</p></>}
   {tool==='zone'&&<><h2>{t('Zones')}</h2><div className="dd-zone-options">{(Object.keys(ZONES) as ZoneKind[]).map(k=><button key={k} className={zoneKind===k?'active':''} onClick={()=>setZoneKind(k)}><i style={{background:ZONES[k]}}/>{t(zoneNames[k])}</button>)}</div><p className="dd-note">{t(instruction)}</p></>}
   {(tool==='road'||tool==='path')&&<><h2>{t('Roads')}</h2><div className="dd-tabs"><button className={tool==='road'?'active':''} onClick={()=>{choose('road');setRouteWidth(15);}}>{t('Road')}</button><button className={tool==='path'?'active':''} onClick={()=>{choose('path');setRouteWidth(8);}}>{t('Footpath')}</button></div>{num('Width',routeWidth,4,50,setRouteWidth)}<p className="dd-note">{t(instruction)}</p><button className="dd-primary" onClick={finishRoad} disabled={draft.length<2}>{t('Finish route')}</button><button onClick={()=>setDraft(d=>d.slice(0,-1))} disabled={!draft.length}>{t('Remove last point')}</button><button onClick={()=>choose('select')}>{t('Cancel route')}</button></>}
   {tool==='bridge'&&<><h2>{t('Bridges')}</h2><p className="dd-note">{t(instruction)}</p>{num('Deck width',bridgeWidth,8,30,setBridgeWidth)}{num('Deck height',bridgeHeight,8,120,setBridgeHeight)}<p className="dd-note">{t('Bamboo frame · 2 mm acrylic deck · 12 mm guards.')}</p>{bridgeStart&&<p className="dd-connect">{t('Connecting from')}: {design.buildings.find(b=>b.id===bridgeStart)?.modelId}</p>}<button onClick={()=>choose('select')}>{t('Cancel')}</button><p className="dd-note">{t('Bridges and decorations have no quantity limit.')}</p></>}
   {(tool==='tree'||tool==='bench')&&<><h2>{t('Decorations')}</h2><div className="dd-tabs"><button className={tool==='tree'?'active':''} onClick={()=>choose('tree')}>{t('Tree')}</button><button className={tool==='bench'?'active':''} onClick={()=>choose('bench')}>{t('Bench')}</button></div><p className="dd-note">{t(instruction)}</p><p className="dd-note">{t('Bridges and decorations have no quantity limit.')}</p></>}
  </aside><section className="dd-workspace" aria-label={t('A2 board')}><div className="dd-toolbar"><div className="dd-tabs"><button className={view==='top'?'active':''} onClick={()=>setView('top')}>{t('Top view')}</button><button className={view==='3d'?'active':''} onClick={()=>{setView('3d');setSelected(null);setPreview(null);setDraft([]);drag.current=null;}}>{t('3D preview')}</button></div><button aria-label={t('Undo')} title="Ctrl+Z" disabled={!past.length} onClick={undo}><Undo2 size={18}/></button><button aria-label={t('Redo')} title="Ctrl+Y" disabled={!future.length} onClick={redo}><Redo2 size={18}/></button><label><input type="checkbox" checked={dimensions} onChange={e=>setDimensions(e.target.checked)}/>{t(view==='3d'?'Selected object dimensions':'Show dimensions')}</label>{view==='top'&&<label><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/>{t('Snap to 5 mm')}</label>}<button className="dd-expand" aria-pressed={expanded} onClick={()=>setExpanded(v=>!v)}>{expanded?<Minimize2 size={17}/>:<Maximize2 size={17}/>}<span>{t(expanded?'Exit expanded view':'Expand workspace')}</span></button></div><p className="dd-instruction">{t(view==='3d'?'Click a building to show its dimensions.':instruction)}</p>
   <div className="dd-stage">{view==='3d'?<DistrictPreview ref={three} design={design} dimensions={dimensions} selected={selected?.id??''} onSelect={id=>setSelected(id?{kind:design.buildings.some(b=>b.id===id)?'buildings':'bridges',id}:null)} errorText={t('3D is unavailable. You can continue in top view.')}/>:<DistrictPlan ref={svg} design={preview??design} selected={selected?.id??''} bridgeStart={bridgeStart} dimensions={dimensions} grid={grid} draft={draft} routeWidth={routeWidth} zoom={zoom} center={viewCenter} onViewport={(next,center)=>{setZoom(next);setViewCenter(center);}} tool={tool} t={t} onDown={down} onMove={e=>{const d=moved(e);if(d)setPreview(d);}} onUp={up} onCancel={()=>{drag.current=null;setPreview(null);}}/>}<div className="dd-view-controls">{view==='top'?<><button aria-label={t('Zoom in')} onClick={()=>{if(b)setViewCenter({x:b.x,y:b.y});setZoom(v=>Math.min(6,v*1.25));}}><Plus size={18}/></button><button aria-label={t('Zoom out')} onClick={()=>{setZoom(v=>Math.max(.5,v/1.25));}}><Minus size={18}/></button><button aria-label={t('Fit site')} onClick={()=>{setZoom(1);setViewCenter({x:297,y:211});}}><Maximize2 size={18}/></button></>:<><button aria-label={t('Zoom in')} onClick={()=>three.current?.zoom(.8)}><Plus size={18}/></button><button aria-label={t('Zoom out')} onClick={()=>three.current?.zoom(1.25)}><Minus size={18}/></button><button aria-label={t('Reset view')} onClick={()=>three.current?.reset()}><Maximize2 size={18}/></button></>}</div></div>
   <div className="dd-stage-footer"><span>{t(view==='top'?'Wheel to zoom · right-drag to pan':'Drag to orbit · wheel to zoom · right-drag to pan')}</span><button onClick={()=>void image()} disabled={exporting}><ImageDown size={16}/>{t(exporting?'Exporting…':'Export image')}</button></div>{collision.length+blocked.length+water.length>0&&<details className="dd-warnings"><summary>{t('Design checks')} ({collision.length+blocked.length+water.length})</summary>{collision.length>0&&<p>{t('Building overlap')}: {collision.join(', ')}</p>}{blocked.length>0&&<p>{t('Building blocks a route')}: {blocked.join(', ')}</p>}{water.length>0&&<p>{t('Building overlaps the river')}: {water.join(', ')}</p>}</details>}
  </section><aside className="dd-inspector" aria-label={t('Object settings')}><h2>{t('Object settings')}</h2>{!current&&<div className="dd-empty"><MousePointer2 size={27}/><p>{t('Select an object to see its dimensions.')}</p></div>}
   {b&&<><ModelThumbnail model={MODEL_MAP[b.modelId]}/><h3>{b.modelId} · {name(b.modelId)}</h3><div className="dd-measure"><strong>{MODEL_MAP[b.modelId].width} × {MODEL_MAP[b.modelId].depth} × {MODEL_MAP[b.modelId].height}</strong><span>W × D × H · mm</span></div><p className="dd-note">{t('All sizes are physical model sizes in mm.')}</p></>}
   {(b||deco)&&<>{num('Position X',(b??deco)!.x,0,594,x=>update({x}))}{num('Position Y',(b??deco)!.y,0,420,y=>update({y}))}{num('Rotation',(b??deco)!.rotation,0,359,rotation=>update({rotation}),'°')}<button onClick={()=>update({rotation:((b??deco)!.rotation+90)%360})}><RotateCw size={16}/>{t('Rotate 90°')}</button></>}
   {z&&<><h3>{t(zoneNames[z.kind])}</h3>{num('Position X',z.x,0,594,x=>update({x}))}{num('Position Y',z.y,0,420,y=>update({y}))}{num('Width',z.w,5,594,w=>update({w}))}{num('Depth',z.d,5,420,d=>update({d}))}<select aria-label={t('Zones')} value={z.kind} onChange={e=>update({kind:e.target.value})}>{Object.keys(ZONES).map(k=><option key={k} value={k}>{t(zoneNames[k as ZoneKind])}</option>)}</select></>}
   {r&&<><h3>{t(r.kind==='road'?'Road':'Footpath')}</h3><div className="dd-measure"><strong>{round(roadLength(r))} mm</strong><span>{t('Length')}</span></div>{num('Width',r.width,4,50,width=>update({width}))}<p className="dd-note">{t('Select route corners to reshape the route.')}</p></>}
   {bridge&&<><h3>{t('Bridges')}</h3><div className="dd-measure"><strong>{round(bridgeGeometry(design,bridge)?.length??0)} mm</strong><span>{t('Bridge span')}</span></div>{num('Deck width',bridge.width,8,30,width=>update({width}))}{num('Deck height',bridge.height,8,120,height=>update({height}))}<p className="dd-note">{t('Bridge endpoints follow their buildings.')} {t('Bamboo frame · 2 mm acrylic deck · 12 mm guards.')}</p></>}
   {current&&<div className="dd-object-actions">{selected?.kind!=='bridges'&&selected?.kind!=='roads'&&<button onClick={duplicate}><Copy size={16}/>{t('Duplicate')}</button>}<button className="dd-danger" onClick={remove}><Trash2 size={16}/>{t('Delete')}</button></div>}
   <details className="dd-object-list"><summary>{t('Placed objects')} ({design.buildings.length+design.bridges.length+design.roads.length+design.zones.length+design.decorations.length})</summary>{(['buildings','bridges','roads','zones','decorations'] as const).map(kind=>design[kind].map((o,i)=><button key={o.id} className={selected?.id===o.id?'active':''} onClick={()=>{choose('select');setSelected({kind,id:o.id});}}>{kind==='buildings'?(o as Building).modelId:t(kind==='bridges'?'Bridges':kind==='roads'?'Roads':kind==='zones'?'Zones':'Decorations')} · {i+1}</button>))}</details>
   <div className="dd-project-fields"><label>{t('Design name')}<input aria-label={t('Design name')} maxLength={80} value={design.name} placeholder={t('Untitled district')} onChange={e=>setDesign(d=>({...d,name:e.target.value}))}/></label><div><label>{t('Class')}<input aria-label={t('Class')} maxLength={30} value={design.className} placeholder="2B" onChange={e=>setDesign(d=>({...d,className:e.target.value}))}/></label><label>{t('Group')}<input aria-label={t('Group')} maxLength={30} value={design.group} placeholder="GROUP 2" onChange={e=>setDesign(d=>({...d,group:e.target.value}))}/></label></div><button onClick={()=>exportParts(design,language)}><Download size={16}/>{t('Parts list')}</button><button className="dd-danger" onClick={async()=>{if(await ask('Clear this design? You can undo this action.')){commit({...emptyDesign(),name:design.name,className:design.className,group:design.group});setSelected(null);choose('select');}}}><Trash2 size={16}/>{t('Clear board')}</button></div><p className="dd-note">{t('Check access and bridge clearance before making the physical model.')}</p><p className="dd-note">{t('Preview uses simplified facades, not cutting or printing files.')}</p>
  </aside></div><footer className="dd-status"><span><Save size={14}/>{t(saved)}</span><span>594 × 420 mm · 1:1</span></footer>{message&&<output className="dd-toast">{t(message)}<button aria-label={t('Cancel')} onClick={()=>setMessage('')}><X size={16}/></button></output>}
 <Dialog open={!!confirmation} onOpenChange={open=>{if(!open)respond(false);}}><DialogContent className="dd-confirm"><DialogTitle>{t('Confirm action')}</DialogTitle><DialogDescription>{t(confirmation?.message??'')}</DialogDescription><div><button onClick={()=>respond(false)}>{t('Cancel')}</button><button onClick={()=>respond(true)}>{t('Confirm')}</button></div></DialogContent></Dialog></main>;
}
