'use client';
/* oxlint-disable jsx-a11y/no-noninteractive-tabindex, jsx-a11y/no-noninteractive-element-interactions -- This focusable SVG application is the drawing canvas, with keyboard shortcuts, pointer editing and right-button panning. */
import {forwardRef,useEffect,useRef,useState,useImperativeHandle,type PointerEventHandler,type PointerEvent as PE} from 'react';
import {SITE,RIVER,MODEL_MAP,ZONES,bridgeGeometry,round,roadLength,type Design,type Point,type Model} from '@/lib/district-design';
import {planFrame,zoomAt} from '@/lib/district-viewport';

const pts=(p:Point[])=>p.map(v=>`${v.x},${v.y}`).join(' ');
export function ModelThumbnail({model:m}:{model:Model}){const project=(x:number,y:number,z:number)=>[x*.8-y*.55,(x+y)*.32-z*.72];const boxes=m.boxes.map(b=>[[b.x,b.y,b.z+b.h],[b.x+b.w,b.y,b.z+b.h],[b.x+b.w,b.y+b.d,b.z+b.h],[b.x,b.y+b.d,b.z+b.h],[b.x,b.y,b.z],[b.x+b.w,b.y,b.z],[b.x+b.w,b.y+b.d,b.z]].map(([x,y,z])=>project(x,y,z)));const all=boxes.flat(),minX=Math.min(...all.map(p=>p[0])),maxX=Math.max(...all.map(p=>p[0])),minY=Math.min(...all.map(p=>p[1])),maxY=Math.max(...all.map(p=>p[1])),blue=m.kind==='print';return <svg viewBox={`${minX-8} ${minY-8} ${maxX-minX+16} ${maxY-minY+16}`} aria-hidden="true">{boxes.map((q,i)=><g key={i} stroke={blue?'#2863a6':'#9a7448'} strokeWidth=".6">{[[0,1,5,4],[1,2,6,5],[0,1,2,3]].map((face,j)=><polygon key={j} points={face.map(k=>q[k].join(',')).join(' ')} fill={(blue?['#458edd','#2c70b9','#87baff']:['#dbb784','#bc955f','#efd5aa'])[j]}/>)}</g>)}</svg>;}
type Props={design:Design;selected:string;bridgeStart:string;dimensions:boolean;grid:boolean;draft:Point[];routeWidth:number;zoom:number;center:Point;tool:string;t:(s:string)=>string;onViewport:(zoom:number,center:Point)=>void;onDown:PointerEventHandler<SVGSVGElement>;onMove:PointerEventHandler<SVGSVGElement>;onUp:PointerEventHandler<SVGSVGElement>;onCancel:()=>void};
export const DistrictPlan=forwardRef<SVGSVGElement,Props>(function DistrictPlan({design:d,selected,bridgeStart,dimensions,grid,draft,routeWidth,zoom,center,tool,t,onViewport,onDown,onMove,onUp,onCancel},ref){
 const canvas=useRef<SVGSVGElement>(null),pan=useRef<{start:DOMPoint;inverse:DOMMatrix;center:Point;pointer:number}|null>(null);
 const [size,setSize]=useState({width:800,height:500});
 useImperativeHandle(ref,()=>canvas.current!,[]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const observer=new ResizeObserver(()=>setSize({width:el.clientWidth,height:el.clientHeight}));observer.observe(el);return()=>observer.disconnect();},[]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();if(pan.current||e.buttons)return;const matrix=el.getScreenCTM();if(!matrix)return;const anchor=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?el.clientHeight:1);const next=zoomAt(center,zoom,zoom*Math.exp(-Math.max(-240,Math.min(240,delta))*.0025),anchor);onViewport(next.zoom,next.center);};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[zoom,center,onViewport]);
 const {width:w,height:h}=planFrame(size.width,size.height,zoom);
 function start(e:PE<SVGSVGElement>){if(e.button===1||e.button===2){e.preventDefault();const inverse=e.currentTarget.getScreenCTM()?.inverse();if(!inverse)return;pan.current={start:new DOMPoint(e.clientX,e.clientY).matrixTransform(inverse),inverse,center:{...center},pointer:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);return;}onDown(e);}
 function move(e:PE<SVGSVGElement>){const p=pan.current;if(p){const next=new DOMPoint(e.clientX,e.clientY).matrixTransform(p.inverse);onViewport(zoom,{x:p.center.x+p.start.x-next.x,y:p.center.y+p.start.y-next.y});}else onMove(e);}
 function end(e:PE<SVGSVGElement>){if(pan.current){pan.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}else onUp(e);}
 return <svg ref={canvas} className="dd-plan" role="application" tabIndex={0} aria-label={t('A2 board')} viewBox={`${center.x-w/2} ${center.y-h/2} ${w} ${h}`} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{pan.current=null;onCancel();}} onContextMenu={e=>e.preventDefault()} style={{cursor:tool==='select'?'default':'crosshair'}}>
  <defs><pattern id="dd-grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M5 0H0V5" fill="none" stroke="#76866f" strokeWidth=".18"/></pattern><marker id="dd-arrow" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="#edb97e"/></marker></defs>
  <rect width="594" height="420" rx="1" fill="#e8ebe3" stroke="#b4c1b1" strokeWidth="1"/><polygon points={pts(SITE)} fill="#d3dfce" stroke="#76906d" strokeWidth="1"/>{grid&&<polygon points={pts(SITE)} fill="url(#dd-grid)" pointerEvents="none"/>}
  {d.zones.map(z=><g key={z.id} data-object={z.id} data-kind="zones"><rect x={z.x} y={z.y} width={z.w} height={z.d} fill={ZONES[z.kind]} fillOpacity=".56" stroke={selected===z.id?'#ad5323':ZONES[z.kind]} strokeWidth={selected===z.id?1.6:.8}/><text x={z.x+3} y={z.y+8} fontSize="5" fill="#233f30" pointerEvents="none">{t({residential:'Residential',commercial:'Commercial',community:'Community',green:'Green space',plaza:'Plaza'}[z.kind])}{dimensions?` · ${z.w} × ${z.d} mm`:''}</text></g>)}
  <g aria-label={t('Fixed river')} pointerEvents="none"><polygon points={pts(RIVER)} fill="#78b8d7" stroke="#4c96b7" strokeWidth="1"/>{[110,150,190,230,270,310].map(y=><path key={y} d={`M23 ${y}q5 -2 10 0t10 0`} fill="none" stroke="#c5e8ee" strokeWidth=".7"/>)}<text x="35" y="210" textAnchor="middle" fill="#24516b" fontSize="6" transform="rotate(-90 35 210)">{t('River')} · 40 × 260 mm</text></g>
  {d.roads.map(r=><g key={r.id} data-object={r.id} data-kind="roads"><polyline points={pts(r.points)} fill="none" stroke={selected===r.id?'#e0a454':'#485454'} strokeWidth={r.width+1} strokeLinejoin="round" strokeLinecap="round"/><polyline points={pts(r.points)} fill="none" stroke={r.kind==='road'?'#64737a':'#aeb4b5'} strokeWidth={r.width} strokeLinejoin="round" strokeLinecap="round"/>{r.kind==='road'&&<polyline points={pts(r.points)} fill="none" stroke="#fff2cb" strokeWidth=".8" strokeDasharray="5 5" pointerEvents="none"/>}{dimensions&&<text x={r.points[0].x+3} y={r.points[0].y-4-r.width/2} fill="#243e37" fontSize="5" paintOrder="stroke" stroke="#e8ebe3" strokeWidth="1.6" pointerEvents="none">{round(roadLength(r))} × {r.width} mm</text>}{selected===r.id&&tool==='select'&&r.points.map((p,i)=><circle data-vertex={i} data-editor-only key={i} cx={p.x} cy={p.y} r="3" fill="#fff" stroke="#9b5625" strokeWidth="1" style={{cursor:'move'}}/>)}</g>)}
  {d.buildings.map(b=>{const m=MODEL_MAP[b.modelId];return <g key={b.id} data-object={b.id} data-kind="buildings" transform={`translate(${b.x} ${b.y}) rotate(${b.rotation})`}><rect x={-m.width/2} y={-m.depth/2} width={m.width} height={m.depth} fill={m.kind==='wood'?'#d2aa75':'#adc8e2'} stroke={selected===b.id||bridgeStart===b.id?'#b25724':'#49728e'} strokeWidth={selected===b.id||bridgeStart===b.id?2:.6}/>{m.boxes.map((p,i)=><rect key={i} x={p.x-m.width/2} y={p.y-m.depth/2} width={p.w} height={p.d} fill={m.kind==='wood'?(i%2?'#d7b984':'#e2cda6'):(p.role==='base'?'#b2cbdc':`hsl(210 65% ${Math.max(42,70-p.z*.18)}%)`)} stroke={m.kind==='wood'?'#9a7e53':'#3770a2'} strokeWidth=".6"/>)}<text textAnchor="middle" y="2" fill="#173448" fontWeight="bold" fontSize="7" paintOrder="stroke" stroke="#ffffffb0" strokeWidth="1.5" pointerEvents="none">{m.id}</text>{dimensions&&<text y={m.depth/2+7} textAnchor="middle" fontSize="5" fill="#173448" paintOrder="stroke" stroke="#e8ebe3" strokeWidth="2" pointerEvents="none">{m.width} × {m.depth} × {m.height} mm</text>}</g>;})}
  {d.bridges.map(b=>{const g=bridgeGeometry(d,b);if(!g)return null;return <g key={b.id} data-object={b.id} data-kind="bridges"><line x1={g.start.x} y1={g.start.y} x2={g.end.x} y2={g.end.y} stroke={selected===b.id?'#ba5d27':'#a28948'} strokeWidth={b.width+1.2}/><line x1={g.start.x} y1={g.start.y} x2={g.end.x} y2={g.end.y} stroke="#b6dadd" strokeOpacity=".72" strokeWidth={b.width-1.2}/><line x1={g.start.x} y1={g.start.y} x2={g.end.x} y2={g.end.y} stroke="#ab8c62" strokeWidth=".7" strokeDasharray="1 18"/>{dimensions&&<text x={(g.start.x+g.end.x)/2} y={(g.start.y+g.end.y)/2-4-b.width/2} textAnchor="middle" fontSize="5" fill="#513e12" paintOrder="stroke" stroke="#fff5d5" strokeWidth="2">{round(g.length)} × {b.width} mm · H {b.height}</text>}</g>;})}
  {d.decorations.map(p=><g key={p.id} data-object={p.id} data-kind="decorations" transform={`translate(${p.x} ${p.y}) rotate(${p.rotation})`}>{p.kind==='tree'?<><circle r="5" fill="#5d9969" stroke={selected===p.id?'#a55c27':'#3e7049'} strokeWidth="1"/><circle r="2.5" fill="#79b77c" pointerEvents="none"/></>:<rect x="-5" y="-2" width="10" height="4" rx="1" fill="#b28c53" stroke={selected===p.id?'#a55c27':'#6d573c'}/>}</g>)}
  {draft.length>0&&<g data-editor-only><polyline points={pts(draft)} fill="none" stroke="#e8a65f" strokeWidth={routeWidth} opacity=".8" strokeLinecap="round" strokeLinejoin="round"/>{draft.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="3" fill="#fff" stroke="#965c2a"/>)}</g>}
  <line x1="0" y1="-12" x2="594" y2="-12" stroke="#edb97e" strokeWidth=".8" markerStart="url(#dd-arrow)" markerEnd="url(#dd-arrow)"/><text x="297" y="-17" fill="#f3d3a8" fontSize="8" textAnchor="middle">594 mm</text><line x1="607" y1="0" x2="607" y2="420" stroke="#edb97e" strokeWidth=".8" markerStart="url(#dd-arrow)" markerEnd="url(#dd-arrow)"/><text x="616" y="210" fill="#f3d3a8" fontSize="8" textAnchor="middle" transform="rotate(90 616 210)">420 mm</text>
  <text x="12" y="18" fill="#496044" fontSize="7" fontWeight="bold">A2 · {t('All sizes are physical model sizes in mm.')}</text><text x="12" y="32" fill="#64735e" fontSize="6">{t('Original outline fitted without stretching.')}</text><text x="12" y="407" fill="#496044" fontSize="7">{[d.className,d.group,d.name].filter(Boolean).join(' · ')}</text>
 </svg>;
});
