'use client';
import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createUrbanModel, type LayerName } from '@/lib/urban-model';
import { BUILDINGS, world } from '@/lib/model-data';

export type ViewerApi = { reset:()=>void; zoom:(factor:number)=>void; focus:()=>void; exportGLB:()=>Promise<void>; };
export type ViewerProps = { view:'iso'|'top'; mode:'material'|'clay'|'wire'; selected:string; visibility:Record<LayerName,boolean>; labels:boolean; heightScale:number; daylight:number; onSelect:(id:string)=>void; onReady:()=>void };
type Runtime = { model:ReturnType<typeof createUrbanModel>; camera:THREE.OrthographicCamera; controls:OrbitControls; sun:THREE.DirectionalLight; selection:THREE.BoxHelper; originals:Map<THREE.MeshStandardMaterial,THREE.Color>; reset:()=>void; renderer:THREE.WebGLRenderer; roadLabels:THREE.Group; };

export const UrbanViewer = forwardRef<ViewerApi, ViewerProps>(function UrbanViewer(props,ref){
 const mount=useRef<HTMLDivElement>(null);const state=useRef(props);state.current=props;const runtime=useRef<Runtime|null>(null);const [ready,setReady]=useState(false);const [error,setError]=useState('');const labelRefs=useRef<(HTMLDivElement|null)[]>([]);
 useImperativeHandle(ref,()=>({
   reset(){runtime.current?.reset();},
   zoom(factor){const r=runtime.current;if(!r)return;r.camera.zoom=THREE.MathUtils.clamp(r.camera.zoom*factor,.45,5);r.camera.updateProjectionMatrix();},
   focus(){const r=runtime.current;if(!r)return;const b=BUILDINGS.find(b=>b.id===state.current.selected);if(!b)return;const [x,z]=world(b.x,b.z);const next=new THREE.Vector3(x,b.h*state.current.heightScale*.3,z);const delta=next.clone().sub(r.controls.target);r.controls.target.copy(next);r.camera.position.add(delta);r.camera.zoom=2.1;r.camera.updateProjectionMatrix();r.controls.update();},
   async exportGLB(){const r=runtime.current;if(!r)throw new Error('模型尚未準備完成');const {exportSceneBinary}=await import('@/lib/export-scene');const result=await exportSceneBinary(r.model.root);const blob=new Blob([result],{type:'model/gltf-binary'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='yuen-long-urban-study.glb';document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),15000);}
 }),[]);

 useEffect(()=>{const host=mount.current;if(!host)return;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{setError('此裝置無法啟動 WebGL 3D');return;}
  renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;host.appendChild(renderer.domElement);
  const scene=new THREE.Scene();scene.background=new THREE.Color('#353b3f');scene.fog=new THREE.Fog('#353b3f',800,1600);
  const camera=new THREE.OrthographicCamera(-300,300,250,-250,.1,2500);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.085;controls.minZoom=.45;controls.maxZoom=5;controls.maxPolarAngle=Math.PI/2.18;controls.minPolarAngle=.015;controls.enablePan=true;controls.screenSpacePanning=true;controls.rotateSpeed=.6;controls.zoomSpeed=.9;controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};controls.touches={ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN};
  scene.add(new THREE.HemisphereLight('#e2ecf4','#7c8071',2.1));const sun=new THREE.DirectionalLight('#fff0d7',3);sun.position.set(-160,310,-180);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-310;sun.shadow.camera.right=310;sun.shadow.camera.top=270;sun.shadow.camera.bottom=-270;sun.shadow.camera.near=20;sun.shadow.camera.far=800;sun.shadow.normalBias=.4;sun.shadow.bias=-.0002;scene.add(sun);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(2600,2600),new THREE.MeshStandardMaterial({color:'#41494c',roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-3.65;floor.receiveShadow=true;scene.add(floor);
  const grid=new THREE.GridHelper(2400,120,'#596367','#515a5d');grid.position.y=-3.6;(grid.material as THREE.Material).transparent=true;(grid.material as THREE.Material).opacity=.28;scene.add(grid);
  const model=createUrbanModel();scene.add(model.root);
  const originals=new Map<THREE.MeshStandardMaterial,THREE.Color>();model.root.traverse(o=>{if(o instanceof THREE.Mesh && o.material instanceof THREE.MeshStandardMaterial)originals.set(o.material,o.material.color.clone());});
  const selection=new THREE.BoxHelper(model.buildingGroups.get(state.current.selected)!,0xf4b276);(selection.material as THREE.LineBasicMaterial).transparent=true;(selection.material as THREE.LineBasicMaterial).opacity=.85;scene.add(selection);
  const roadLabels=new THREE.Group();scene.add(roadLabels);
  function roadText(text:string,x:number,z:number,w:number,angle=0){const c=document.createElement('canvas');c.width=1024;c.height=96;const ctx=c.getContext('2d');if(!ctx)return;ctx.fillStyle='#dbe0d8';ctx.font='500 45px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,48);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;const m=new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,opacity:.74,side:THREE.DoubleSide});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,w*96/1024),m);const [wx,wz]=world(x,z);mesh.position.set(wx,.7,wz);mesh.rotation.set(-Math.PI/2,0,angle);roadLabels.add(mesh);}
  roadText('TAI TONG ROAD',555,46,57);roadText('KAU YUK ROAD',520,483,46);roadText('HONG LOK RD',449,254,31,Math.PI/2);roadText('YU KING SQUARE',749,236,40);roadText('CHUNG SING PATH',95,215,34,Math.PI/2);
  const resize=()=>{const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h);const aspect=w/h,span=Math.max(288,485/aspect);camera.left=-span*aspect/2;camera.right=span*aspect/2;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();};
  const reset=()=>{camera.zoom=1;controls.target.set(-13,4,0);if(state.current.view==='top'){camera.position.set(-13,600,.1);controls.enableRotate=false;}else{camera.position.set(207,330,440);controls.enableRotate=true;}camera.updateProjectionMatrix();controls.update();};
  runtime.current={model,camera,controls,sun,selection,originals,reset,renderer,roadLabels};resize();reset();
  const observer=new ResizeObserver(resize);observer.observe(host);
  const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=[0,0];
  const onDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY];};const onUp=(e:PointerEvent)=>{if(e.button!==0||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;if(!state.current.visibility.buildings)return;const b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(model.layers.buildings.children,true)[0];if(hit){let o:THREE.Object3D|null=hit.object;while(o && !o.userData.id)o=o.parent;if(o?.userData.id)state.current.onSelect(o.userData.id);}};
  const onKey=(e:KeyboardEvent)=>{if(e.key==='Home'){e.preventDefault();reset();}if(e.key==='+'||e.key==='='){camera.zoom=Math.min(5,camera.zoom*1.15);camera.updateProjectionMatrix();}if(e.key==='-'){camera.zoom=Math.max(.45,camera.zoom/1.15);camera.updateProjectionMatrix();}if(e.key.startsWith('Arrow')){e.preventDefault();const delta=new THREE.Vector3(e.key==='ArrowLeft'?-10:e.key==='ArrowRight'?10:0,0,e.key==='ArrowUp'?-10:e.key==='ArrowDown'?10:0);camera.position.add(delta);controls.target.add(delta);}};
  const onContextLost=(e:Event)=>{e.preventDefault();setError('3D 繪圖連線中斷，請重新載入頁面。');};
  renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',onUp);renderer.domElement.addEventListener('webglcontextlost',onContextLost);host.addEventListener('keydown',onKey);
  let frame=0;const projected=new THREE.Vector3();const animate=()=>{frame=requestAnimationFrame(animate);if(document.hidden)return;controls.update();selection.update();renderer.render(scene,camera);const compass=host.parentElement?.querySelector<SVGElement>("[data-compass]");if(compass){const north=new THREE.Vector3(controls.target.x,0,controls.target.z-40).project(camera);const origin=new THREE.Vector3(controls.target.x,0,controls.target.z).project(camera);compass.style.transform="rotate("+(Math.atan2((north.x-origin.x)*host.clientWidth,(north.y-origin.y)*host.clientHeight)*180/Math.PI)+"deg)";}const p=state.current;const selected=BUILDINGS.find(b=>b.id===p.selected);const positions=[[372,318,11],[167,390,10],selected?[selected.x,selected.z,selected.h*p.heightScale+9]:[0,0,0]];positions.forEach(([x,z,y],i)=>{const label=labelRefs.current[i];if(!label)return;const [wx,wz]=world(x,z);projected.set(wx,y,wz).project(camera);const show=p.labels&&(i===2?p.visibility.buildings:p.visibility.parks)&&projected.z>=-1&&projected.z<=1;label.style.display=show?'block':'none';label.style.left=((projected.x+1)/2*host.clientWidth)+'px';label.style.top=((-projected.y+1)/2*host.clientHeight)+'px';});};animate();setReady(true);state.current.onReady();
  return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',onDown);renderer.domElement.removeEventListener('pointerup',onUp);renderer.domElement.removeEventListener('webglcontextlost',onContextLost);host.removeEventListener('keydown',onKey);const geometries=new Set<THREE.BufferGeometry>();const materials=new Set<THREE.Material>();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.LineSegments){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>{if('map' in m && m.map instanceof THREE.Texture)m.map.dispose();m.dispose();});renderer.dispose();renderer.domElement.remove();runtime.current=null;};
 },[]);
 useEffect(()=>{runtime.current?.reset();},[props.view,ready]);
 useEffect(()=>{const r=runtime.current;if(!r)return;Object.entries(props.visibility).forEach(([k,v])=>r.model.layers[k as LayerName].visible=v);r.roadLabels.visible=props.visibility.roads&&props.labels;r.selection.visible=props.visibility.buildings;r.model.layers.buildings.scale.y=props.heightScale;r.model.root.updateMatrixWorld(true);const group=r.model.buildingGroups.get(props.selected);if(group)r.selection.setFromObject(group);},[props.visibility,props.heightScale,props.selected,props.labels,ready]);
 useEffect(()=>{const r=runtime.current;if(!r)return;r.originals.forEach((c,m)=>{m.wireframe=props.mode==='wire';m.color.copy(props.mode==='clay'?new THREE.Color('#c8cbd0'):c);});},[props.mode,ready]);
 useEffect(()=>{const sun=runtime.current?.sun;if(!sun)return;const angle=(props.daylight-6)/12*Math.PI;sun.position.set(Math.cos(angle)*240,Math.max(55,Math.sin(angle)*310),-150);sun.intensity=2.2+Math.sin(angle)*.8;sun.color.set(props.daylight>15?'#ffd2a0':'#fff0d7');},[props.daylight,ready]);
 const selected=BUILDINGS.find(b=>b.id===props.selected);
 return <><div ref={mount} className="scene-canvas" tabIndex={0} role="application" aria-label="元朗 3D 街區。拖曳旋轉，滾輪縮放，右鍵平移。方向鍵平移，Home 重設。"/>{!ready&&!error&&<div className="scene-loading">正在建立 3D 街區…</div>}{error&&<div className="canvas-error" role="alert">{error}<p>請使用支援 WebGL 的瀏覽器並啟用硬體加速。原圖對照仍可使用。</p></div>}{['元朗兒童遊樂場','鐘聲徑遊樂場',selected?.name||''].map((label,i)=><div key={i} ref={el=>{labelRefs.current[i]=el;}} className={'scene-label '+(i===2?'selected-label':'')} style={{display:'none'}}><span className="label-dot"/>{label}</div>)}</>;
});

