export const DISTRICT_ZH:Record<string,string>={
 'River':'河流','Fixed river':'固定河流','Fit site':'顯示全區','Expand workspace':'放大工作區','Exit expanded view':'退出放大',
 'Selected object dimensions':'選取物件尺寸','Click a building to show its dimensions.':'點選建築，才會顯示該建築的尺寸。',
 'Wheel to zoom · right-drag to pan':'滾輪縮放 · 右鍵拖曳平移','Bamboo frame · 2 mm acrylic deck · 12 mm guards.':'竹籤支架 · 2 mm 亞加力膠板橋面 · 12 mm 欄板。',
 'Design checks':'檢查設計','Building overlaps the river':'建築與河流重疊',
 'Confirm action':'確認操作','Confirm':'確認',
 'Yuen Long District':'元朗街區','District design':'街區設計','A2 board':'A2 底板','Plan in millimetres. Build at the same size.':'以毫米規劃，按相同尺寸製作。',
 'Select & move':'選取／移動','Zones':'土地分區','Roads':'道路','Buildings':'建築物','Bridges':'天橋','Decorations':'裝飾',
 'Printed':'3D 打印','Wooden':'木板建築','Residential':'住宅','Commercial':'商業','Community':'學校／社區','Green space':'綠化','Plaza':'廣場',
 'Road':'馬路','Footpath':'行人路','Tree':'樹木','Bench':'座椅','Top view':'俯視設計','3D preview':'3D 預覽',
 'Undo':'復原','Redo':'重做','Show dimensions':'顯示尺寸','Snap to 5 mm':'對齊 5 mm 格線','Save design':'下載設計檔','Open design':'開啟設計檔','Export image':'下載圖片','Parts list':'下載模型清單','Clear board':'清空底板',
 'Design name':'設計名稱','Class':'班別','Group':'組別','Untitled district':'我的街區','Design tools':'設計工具','Model library':'建築範本','Object settings':'物件設定','Placed objects':'已放置物件',
 'Width':'闊度','Depth':'深度','Height':'高度','Deck height':'橋面高度','Deck width':'橋面闊度','Length':'長度','Rotation':'旋轉角度','Position X':'左右位置 X','Position Y':'上下位置 Y',
 'Rotate 90°':'旋轉 90°','Duplicate':'複製','Delete':'刪除','Cancel':'取消','Finish route':'完成路線','Remove last point':'移除上一點','Reset view':'重設視角',
 'Click a building, zone or decoration, then drag to move it.':'點選建築、分區或裝飾，再拖曳移動。','Choose a model, then click inside the site to place it.':'選擇範本，再點街區內的位置放置。',
 'Drag a rectangle inside the site to create a zone.':'在街區內拖出長方形，建立用途分區。','Click to add corners. Finish the route when ready.':'逐點加入轉角，完成後按「完成路線」。','Click two different buildings to connect a bridge.':'先點第一座建築，再點第二座建築，連接天橋。','Now click the second building.':'現在點選第二座建築。','Click inside the site to place a decoration.':'點街區內的位置放置裝飾。',
 'Select an object to see its dimensions.':'選取物件，查看尺寸及設定。','Model dimensions: W × D × H. Base plates included.':'模型尺寸：闊 × 深 × 高，已包括模型底板。','One complete model counts as one building.':'每套完整範本計作一件建築模型。','Bridges and decorations have no quantity limit.':'天橋和裝飾物不限數量。',
 'Site boundary':'街區設計範圍','Original outline fitted without stretching.':'原街區輪廓等比例放入底板。','Outside site':'街區範圍外','Building overlap':'建築有重疊','Check access and bridge clearance before making the physical model.':'製作前檢查入口、道路及天橋下方空間。',
 'Maximum 6 printed buildings.':'最多只可放置 6 件 3D 打印建築。','Maximum 4 wooden buildings.':'最多只可放置 4 件木板建築。','Keep the whole object inside the site boundary.':'整件物件都要放在街區範圍內。','Choose two separated buildings with walls at this deck height.':'請選擇兩座分開、而且在此橋面高度有牆面的建築。','The bridge must stay inside the site boundary.':'整條天橋都要留在街區範圍內。',
 'Invalid design file. Your current design is unchanged.':'設計檔無效，目前的設計沒有被更改。','File is too large. Open a design file smaller than 2 MB.':'檔案太大，請開啟小於 2 MB 的設計檔。','Design loaded.':'已載入設計。','Design downloaded.':'已下載設計檔。','Saved in this browser':'已儲存在此瀏覽器','Local saving unavailable. Download your design to keep it.':'無法自動儲存，請下載設計檔保留作品。','An unreadable saved design was found. Download it before starting over.':'發現無法讀取的已存設計，請先下載備份，再開始新設計。','Download saved backup':'下載已存備份','Start a new design':'開始新設計',
 'Clear this design? You can undo this action.':'清空目前設計？之後可以按「復原」。','Replace this design with the selected file? You can undo this action.':'以選取的檔案取代目前設計？之後可以按「復原」。','No space nearby. Choose a different position.':'附近沒有足夠空間，請選擇其他位置。','Image downloaded.':'已下載圖片。','Image export failed. Please try again.':'圖片下載失敗，請再試一次。','3D is unavailable. You can continue in top view.':'此裝置無法顯示 3D，仍可使用俯視設計。',
 'Add at least two different points.':'請加入至少兩個不同位置。','No objects yet':'尚未放置物件','All sizes are physical model sizes in mm.':'所有尺寸均為實體模型尺寸，單位 mm。','Drag to orbit · wheel to zoom · right-drag to pan':'拖曳旋轉 · 滾輪縮放 · 右鍵拖曳平移','Edit positions in top view.':'請在俯視設計中移動物件。','Select route corners to reshape the route.':'拖曳路線的圓點，可修改轉角位置。','Bridge endpoints follow their buildings.':'移動建築時，天橋兩端會跟隨更新。','Deck is 3 mm thick; rails are 12 mm high.':'橋面厚 3 mm；欄杆高 12 mm。','Preview uses simplified facades, not cutting or printing files.':'預覽採用簡化立面，並非切割或打印檔案。',
 'Ready':'可以開始設計','Connecting from':'連接起點','Cancel route':'取消路線','Delete this building and its connected bridges?':'刪除此建築及相連的天橋？','Building blocks a route':'建築與路線重疊','Move':'移動','To':'至','Exporting…':'正在匯出…','Fit board':'顯示全板','Zoom in':'放大','Zoom out':'縮小','Bridge span':'天橋跨度','Use top view to edit.':'切換至俯視設計，即可編輯。',
};
export const districtText=(key:string,language:string)=>language==='en'?key:(DISTRICT_ZH[key]??key);
